name: Generate Snake Animation

on:
  schedule:
    # Jalankan setiap 12 jam
    - cron: "0 */12 * * *"
  # Memungkinkan menjalankan workflow secara manual dari tab Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Membuat animasi snake
      - uses: Platane/snk@v3
        with:
          github_user_name: wrdhn
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
      
      # Push ke branch output
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
